### ISSUE TITLE
\w yarn it seems possible to end up in a broken mode re:version check

### ISSUE THREAD

**Issue by stefanpenner** [rwjblue/ember-runtime-enumerable-includes-polyfill#4]
```

[ember 11/21/16 1:26:40] Invalid Version: undefined
[ember 11/21/16 1:26:40] TypeError: Invalid Version: undefined
[ember 11/21/16 1:26:40]     at new SemVer (/home/mseritan/dev/voyager/voyager-web_trunk/node_modules/ember-cli-version-checker/node_modules/semver/semver.js:281:11)
[ember 11/21/16 1:26:40]     at compare (/home/mseritan/dev/voyager/voyager-web_trunk/node_modules/ember-cli-version-checker/node_modules/semver/semver.js:571:10)
[ember 11/21/16 1:26:40]     at Function.lt (/home/mseritan/dev/voyager/voyager-web_trunk/node_modules/ember-cli-version-checker/node_modules/semver/semver.js:605:10)
[ember 11/21/16 1:26:40]     at DependencyVersionChecker.(anonymous function) [as lt] (/home/mseritan/dev/voyager/voyager-web_trunk/node_modules/ember-cli-version-checker/index.js:68:26)
[ember 11/21/16 1:26:40]     at CoreObject.module.exports.included (/home/mseritan/dev/voyager/voyager-web_trunk/node_modules/ember-runtime-enumerable-includes-polyfill/index.js:18:33)
[ember 11/21/16 1:26:40]     at CoreObject.superWrapper [as included] (/home/mseritan/dev/voyager/voyager-web_trunk/node_modules/ember-cli/node_modules/core-object/lib/assign-properties.js:32:18)
[ember 11/21/16 1:26:40]     at /home/mseritan/dev/voyager/voyager-web_trunk/node_modules/ember-cli/lib/models/addon.js:258:34
[ember 11/21/16 1:26:40]     at Array.map (native)
[ember 11/21/16 1:26:40]     at CoreObject.eachAddonInvoke (/home/mseritan/dev/voyager/voyager-web_trunk/node_modules/ember-cli/lib/models/addon.js:256:24)
[ember 11/21/16 1:26:40]     at CoreObject.extend.included (/home/mseritan/dev/voyager/voyager-web_trunk/node_modules/ember-cli/lib/models/addon.js:433:10)
[ember 11/21/16 1:26:40]     at CoreObject.superWrapper [as included] (/home/mseritan/dev/voyager/voyager-web_trunk/node_modules/ember-cli/node_modules/core-object/lib/assign-properties.js:32:18)
[ember 11/21/16 1:26:40]     at CoreObject.module.exports.included (/home/mseritan/dev/voyager/voyager-web_trunk/node_modules/ember-data/index.js:128:26)
[ember 11/21/16 1:26:40]     at CoreObject.superWrapper [as included] (/home/mseritan/dev/voyager/voyager-web_trunk/node_modules/ember-cli/node_modules/core-object/lib/assign-properties.js:32:18)
[ember 11/21/16 1:26:40]     at EmberApp.<anonymous> (/home/mseritan/dev/voyager/voyager-web_trunk/node_modules/ember-cli/lib/broccoli/ember-app.js:468:15)
[ember 11/21/16 1:26:40]     at Array.filter (native)
[ember 11/21/16 1:26:40]     at EmberApp._notifyAddonIncluded (/home/mseritan/dev/voyager/voyager-web_trunk/node_modules/ember-cli/lib/broccoli/ember-app.js:463:45)
[ember 11/21/16 1:26:40]     at new EmberApp (/home/mseritan/dev/voyager/voyager-web_trunk/node_modules/ember-cli/lib/broccoli/ember-app.js:138:8)
[ember 11/21/16 1:26:40]     at getAppTree (/home/mseritan/dev/voyager/voyager-web_trunk/core/application/ember-cli-build.js:153:9)
[ember 11/21/16 1:26:40]     at /home/mseritan/dev/voyager/voyager-web_trunk/li-builder/index.js:157:19
[ember 11/21/16 1:26:40]     at Array.map (native)
[ember 11/21/16 1:26:40]     at CoreObject.setupBroccoliBuilder (/home/mseritan/dev/voyager/voyager-web_trunk/li-builder/index.js:145:30)
[ember 11/21/16 1:26:40]     at CoreObject.module.exports.Task.extend.init (/home/mseritan/dev/voyager/voyager-web_trunk/node_modules/ember-cli/lib/models/builder.js:54:10)
[ember 11/21/16 1:26:40]     at CoreObject.superWrapper [as init] (/home/mseritan/dev/voyager/voyager-web_trunk/node_modules/ember-cli/node_modules/core-object/lib/assign-properties.js:32:18)
[ember 11/21/16 1:26:40]     at CoreObject.Class (/home/mseritan/dev/voyager/voyager-web_trunk/node_modules/ember-cli/node_modules/core-object/core-object.js:32:33)
[ember 11/21/16 1:26:40]     at CoreObject.module.exports.Task.extend.run (/home/mseritan/dev/voyager/voyager-web_trunk/node_modules/ember-cli/lib/tasks/build.js:15:19)
[ember 11/21/16 1:26:40]     at CoreObject.<anonymous> (/home/mseritan/dev/voyager/voyager-web_trunk/node_modules/ember-cli/lib/commands/test.js:164:27)
[ember 11/21/16 1:26:40]     at tryCatch (/home/mseritan/dev/voyager/voyager-web_trunk/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:538:12)
[ember 11/21/16 1:26:40]     at invokeCallback (/home/mseritan/dev/voyager/voyager-web_trunk/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:553:13)
```

**Comment by rwjblue** [comment]
The error is occurring because it is possible for the [_getEmberVersion](https://github.com/rwjblue/ember-runtime-enumerable-includes-polyfill/blob/f7ed15900351b002692373682fadcdb407f41a13/index.js#L23-L33) method can return `undefined` if neither `bower_components/ember/.bower.json` or `bower_components/ember/bower.json` contain a valid `version` property.

I am not quite sure why this would be the case, but a guess was that `yarn` was removing `bower_components` (older versions of `yarn` would wipe `bower_components` upon every `yarn install` invocation).  

Either way, we can make it not blow up like this when the Ember version is not found.  It will just have to "deopt" and include the polyfill (which is also not ideal), but we can include a warning if that happens.

**Comment by stefanpenner** [comment]
> I am not quite sure why this would be the case, but a guess was that yarn was removing bower_components (older versions of yarn would wipe bower_components upon every yarn install invocation).

Strange, we have a reproduction at work. Maybe we can figure out whatsup.

**Comment by rwjblue** [comment]
@stefanpenner - Ya, the issue is that the `.bower.json` / `bower.json` file doesn't contain a `version` key.  Still working on why...

**Comment by stefanpenner** [comment]
@rwjblue ah, this may be a LinkedIn'ism. Lets figure this out today
